In [9]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import open3d as o3d
import os
import sys

a,b,c,d =  [0.91785764, 1.54344418, 5.15748007], \
           [0.9958691 , 1.53299923, 4.91475091], \
           [0.9228009 , 1.79894896, 5.15487844], \
           [1.00319548, 1.78943029, 4.9116984 ]
           
# 在open3d空间中绘制abcd四个点
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(np.array([a,b,c,d]))
# pcd.points = o3d.utility.Vector3dVector(np.array([a,b]))
o3d.visualization.draw_geometries([pcd])

In [18]:
# 读取npy文件
import numpy as np

npy_dir = '/home/ubunto/Project/konglx/pcd/2dgs/2d-gaussian-splatting-main/output/dalian_xinghaiwandaqiao_rgb/hit_points_img_id=0032_makers.npy'

npy_read_marker = np.load(npy_dir)
# 在open3d空间中绘制abcd四个点
pcd_defects = o3d.geometry.PointCloud()
pcd_defects.points = o3d.utility.Vector3dVector(npy_read_marker)
# pcd.points = o3d.utility.Vector3dVector(np.array([a,b]))
o3d.visualization.draw_geometries([pcd_defects])
print(npy_read_marker, type(npy_read_marker))

[[1.33295657 1.07347353 4.37686977]
 [1.33430732 1.07343609 4.37502854]
 [1.33576978 1.07340905 4.3732375 ]
 ...
 [0.9958691  1.53299923 4.91475091]
 [0.9228009  1.79894896 5.15487844]
 [1.00319548 1.78943029 4.9116984 ]] <class 'numpy.ndarray'>


In [10]:
# 计算3D点的距离
import numpy as np
import cv2
import matplotlib.pyplot as plt

p1 =npy_read_marker[-4]
p2 =npy_read_marker[-3]
p3 =npy_read_marker[-2]
p4 =npy_read_marker[-1]

# 定义函数，计算3D点的距离
def distance(point1, point2):
    return np.sqrt((point1[0]-point2[0])**2 + (point1[1]-point2[1])**2 + (point1[2]-point2[2])**2)

d1 = distance(p1, p2)
d2 = distance(p2, p3)
d3 = distance(p3, p4)
d4 = distance(p4, p1)

print("d1 = ", d1)
print("d2 = ", d2)
print("d3 = ", d3)
print("d4 = ", d4)

d1 =  0.25517117430737124
d2 =  0.36569037156672035
d3 =  0.25630143375403613
d4 =  0.35805074890280614


In [1]:
# hit_points_colors_img_id=0032_makers.npy读取并open3d显示
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os
import sys
import open3d as o3d

# 读取npy文件
npy_file_dir = '/home/ubunto/Project/konglx/pcd/2dgs/2d-gaussian-splatting-main/output/dalian_xinghaiwandaqiao_rgb/hit_points_colors_img_id=0032_makers.npy'

npy_reader = np.load(npy_file_dir, allow_pickle=True)
npy_dict = npy_reader.tolist()
print(npy_dict.keys())
points = npy_dict['all_points_list:']
colors = npy_dict['all_colors_list:']
cls_num = npy_dict['only_defects_cls_length:']
print('only_defects_cls_length:', cls_num )

# # 在open3d空间中绘制abcd四个点
pcd_points_colors = o3d.geometry.PointCloud()
pcd_points_colors.points = o3d.utility.Vector3dVector(points)
pcd_points_colors.colors = o3d.utility.Vector3dVector(colors)
# pcd.points = o3d.utility.Vector3dVector(np.array([a,b]))
# 显示坐标轴
o3d.visualization.draw_geometries([pcd_points_colors, o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=[0, 0, 0])])
# o3d.visualization.draw_geometries([pcd_points_colors])
# print(npy_read_marker, type(npy_read_marker))

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
dict_keys(['all_points_list:', 'all_colors_list:', 'only_defects_cls_length:'])
only_defects_cls_length: {38: 526, 75: 11852}


In [10]:
# hit_points_colors_img_id=0032_makers.npy读取并open3d显示
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os
import sys
import open3d as o3d

# 读取npy文件
npy_file_dir = '/home/ubunto/Project/konglx/pcd/2dgs/2d-gaussian-splatting-main/output/dalian_xinghaiwandaqiao_rgb/hit_points_colors_img_id=0032_makers.npy'

npy_reader = np.load(npy_file_dir, allow_pickle=True)
npy_dict = npy_reader.tolist()
print(npy_dict.keys())
points = npy_dict['all_points_list:']
colors = npy_dict['all_colors_list:']
cls_num = npy_dict['only_defects_cls_length:']
print('only_defects_cls_length:', cls_num )

# # 在open3d空间中绘制abcd四个点
pcd_points_colors = o3d.geometry.PointCloud()
pcd_points_colors.points = o3d.utility.Vector3dVector(points[:526])
pcd_points_colors.colors = o3d.utility.Vector3dVector(colors[:526])
# pcd.points = o3d.utility.Vector3dVector(np.array([a,b]))
# 显示坐标轴
o3d.visualization.draw_geometries([pcd_points_colors, o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=[0, 0, 0])])

dict_keys(['all_points_list:', 'all_colors_list:', 'only_defects_cls_length:'])
only_defects_cls_length: {38: 526, 75: 11852}


In [8]:
# https://blog.51cto.com/u_16213413/12959424 
# 提取3d点骨架

# 导入必要的库
import open3d as o3d
import numpy as np

# 加载点云数据
def load_point_cloud(file_path):
    pcd = o3d.io.read_point_cloud(file_path)
    return pcd

# 可视化点云
def visualize_point_cloud(pcd):
    o3d.visualization.draw_geometries([pcd])

# 主程序
if __name__ == "__main__":
    # pcd = load_point_cloud("path/to/your/pointcloud.pcd")
    visualize_point_cloud(pcd_points_colors)

In [9]:
from sklearn.decomposition import PCA
from sklearn.cluster import DBSCAN

# 点云骨架提取函数
def skeleton_extraction(pcd):
    points = np.asarray(pcd.points)

    # 使用DBSCAN进行聚类
    clustering = DBSCAN(eps=0.05, min_samples=10).fit(points)

    # 提取聚类中心作为骨架
    unique_labels = set(clustering.labels_)
    skeletal_points = []

    for label in unique_labels:
        if label == -1:  # 噪声点
            continue
        cluster_points = points[clustering.labels_ == label]
        pca = PCA(n_components=1)
        pca.fit(cluster_points)
        skeletal_points.append(pca.mean_)

    return np.array(skeletal_points)

# 主程序
if __name__ == "__main__":
    # pcd = load_point_cloud("path/to/your/pointcloud.pcd")
    skeletal_points = skeleton_extraction(pcd_points_colors)

    # 可视化骨架
    skeletal_pcd = o3d.geometry.PointCloud()
    skeletal_pcd.points = o3d.utility.Vector3dVector(skeletal_points)
    visualize_point_cloud(skeletal_pcd)